### ISSUE TITLE
Future request: custom capcode

### ISSUE THREAD

**Issue by sebastiaan001** [cyberjunky/home-assistant-p2000#1]
Would it be possible to get te option to select capcode's so i can make a alert in my home when my korps/piket capcode's get alarmed?

**Comment by cyberjunky** [comment]
Sure, to be honest there use to be a search string option, but it seems I dropped it at one time.
Can you give a few examples of capcodes? There is no standard msg structure for it it seems?
So maybe a 'if msgtest contains x text option' should cover it...

**Comment by sebastiaan001** [comment]
nice! I use the code's:  0804501, 0804504, 0804500, 0804496 and a few others in that range.

**Comment by cyberjunky** [comment]
I just released 1.0.5
Add 'capcodes' option to your config with a list of codes you want to filter on, on top of other params, seperated by a comma.
You can also add the capcode text (is also stored in attribute) to your notification (see automation example)

**Comment by sebastiaan001** [comment]
Thanks, wil test it!
