### ISSUE TITLE
default radius not obeyed

### ISSUE THREAD

**Issue by r3mcos3** [cyberjunky/home-assistant-p2000#10]
new issue arized, 
this is my config.

```
- platform: p2000
  name: Brabant
  regios: 21
  disciplines: 1,2,3,4
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
```
i don't have radius in my config because off default is 5000

`radius (Optional): Only display on calls within this range in meters, it uses the lat/lon from your home-assistant.conf file as center or the optional values. (default = 5000)`

but in the picture you see it don't obey the default 

![Untitled](https://user-images.githubusercontent.com/45529818/76899999-d967d600-6898-11ea-8bb2-e3f2cc467406.png)

**Comment by cyberjunky** [comment]
The behavior has been changed in last version, I removed the default radius value, so you are able to catch all regio or capcode events without having to specify a large radius.
I forgot to update the documentation, just did, thanks for reporting.
