### ISSUE TITLE
P2000 events need formatting

### ISSUE THREAD

**Issue by ManCaveMedia** [cyberjunky/home-assistant-p2000#11]
P2000 events are correctly shown on the map, but unfortunately the're not that easy to read, because of the lack of formatting. It would be nice if we could get them in some sort of ordered list that's a little more friendly to the eye.

**Comment by cyberjunky** [comment]
Do you have some graphics to show? To be honest I don't use the map display myself.

**Comment by ManCaveMedia** [comment]
It's not about the map display. It's about the text that's displayed on the sensor card. If you look at the screenshot in the readme (the 2 sensor cards on the left of the small map) you hopefully see what I mean.

Text looks like:
P 2 Brandgerucht Lieve Vrouwestraat Amersfoort 090131 Mon, 23 Mar 2020 12:55:15 +0100

It would be nice if we could format it like, for example:
23-03-2020 - 13:55:15
P2: Brandgerucht (090131)
Lieve Vrouwestraat, Amersfoort

**Comment by cyberjunky** [comment]
Can you make a screen shot?
I cannot format a sensor value, if you put it in a seperate lovelace card it looks like this, which I find perfect to be honest.

![Screenshot from 2020-03-23 18-17-39](https://user-images.githubusercontent.com/5447161/77343932-c048a480-6d32-11ea-8053-b0de913bb936.png)

**Comment by cyberjunky** [comment]
You can also use a logbook card (see in hacs)
 ```yaml
             - type: 'custom:logbook-card'
                entity: sensor.p2000
                max_items: 3
```
That looks like this:
![Screenshot from 2020-03-23 18-20-16](https://user-images.githubusercontent.com/5447161/77344201-1ae20080-6d33-11ea-9f84-0a5d04668298.png)
 If you set max items to 1 I think you have what you need. Don't know about possible click actions though

**Comment by ManCaveMedia** [comment]
I guess we see the same thing, but have a different opinion.
No matter what card type we use, the event is always a long string with (almost) no comma's, line breaks, etc.
Also, the date is not formated according to the language settings. And I don't like how I have to add up the extra +0100 at the end of the string to know the correct time.

**Comment by cyberjunky** [comment]
I can leave out all extra stuff and make it look like www.livep2000.nl output, but that's not what I want.
With the date part you have a point, it's on my list to make better.

**Comment by ManCaveMedia** [comment]
> I can leave out all extra stuff and make it look like [www.livep2000.nl](http://www.livep2000.nl) output, but that's not what I want.
I fully understand if you don't like the bright colors. I'm not a fan of that either. However, the line breaks to separate the date from the events really helps to get a better overview.
> With the date part you have a point, it's on my list to make better.
That would be great! Thank you!

**Comment by cyberjunky** [comment]
I close this for now, hard to implement with all the different event layouts.
