### ISSUE TITLE
Detection of blocking I/O in the event loop WARNING in P2000

### ISSUE THREAD

**Issue by ualex73** [cyberjunky/home-assistant-p2000#13]
Home Assistant 0.109 has a new 'feature' called 'Detection of blocking I/O in the event loop', reported already in the rc:
https://rc--home-assistant-docs.netlify.app/blog/2020/04/21/release-109/

The warning means there is a blocking call in asyncio code, which isn't correct (can cause e.g. delays).

The home-assistant.log message:
`
2020-04-24 08:06:00 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for p2000 doing I/O at custom_components/p2000/sensor.py, line 109: modified=None if not self._feed else self._feed.get("modified"),
`

To the 'self._feed.get("modified")' needs to be wrapped into a home assistant helper, like: 
result = await hass.async_add_executor_job(hub.update)

This is documented in:
https://developers.home-assistant.io/docs/asyncio_working_with_async/

**Comment by dutch-erik** [comment]
Hope this can be solved soon or can it be solved manually?
Database is increasing due to errors.

**Comment by cyberjunky** [comment]
I fixed it in release 1.0.12, it will appear in HACS within a few minutes.
