### ISSUE TITLE
Capcode problem

### ISSUE THREAD

**Issue by Jarnoklein** [cyberjunky/home-assistant-p2000#15]
Hello,

I use your p2000 sensor for a while now, but something seems to go wrong with the capcode’s. I use the sensor to automate the lights because i’m a member of the fire crew. 

When i’m testing with the capcode of a monitor from amsterdam everything is okay and works.

When i use my own capcode (502050 without the leading 0) nothing happens..
Country settings is also correct

**Comment by cyberjunky** [comment]
Can you rub with debug enabled and check for 502050?
Is your station using FireServiceRota or BrandweerRooster by any change?
I'm developing a integration for that, using websocket, it's very fast, you get notified via Home Assistant before your beeper goes off ;-)

**Comment by cyberjunky** [comment]
It can even use the text to speech contents of the incident text while you are putting on your clothes ;)
https://github.com/cyberjunky/home-assistant-fireservicerota
Anyway I have a debug session running with your capcode.

**Comment by Jarnoklein** [comment]
Thanks!
I think I’ve got it already..
They don’t use locations for us
I didn’t set the nolocation setting to True, maybe it’s working now..
Your integration sounds good!
At our station we are using the precom system

I hope that in the time that i put on my clothes the light is turned on. Don’t know the delay but according to the rss feeds it can be up to 1 minute or so

**Comment by Jarnoklein** [comment]
We wait till the next call and see what happens! ;)
