### ISSUE TITLE
Another search option (like *GRIP*)

### ISSUE THREAD

**Issue by Dinges28** [cyberjunky/home-assistant-p2000#18]
Hi,

I like the p2000 sensor! Thank you for the implementation.

What I would love to have is, scan in every region for the text "GRIP" or "Lifeliner", for big incidents notification.

Could you implement that?

**Comment by cyberjunky** [comment]
So check for it as last filter, only trigger if message text contains this value if set?
Maybe call it 'contains'

**Comment by cyberjunky** [comment]
I have implemented this in version 1.0.15, usage:

```yaml
contains: GRIP
```

Please test.

**Comment by pietke** [comment]
> To be honest it only supports one keyword.
> I can make it behave like 'capcodes', since that does exactly the same, search the event text for one or more text strings.

Hi Cyberjunky, 
I want to get a notification when something happened in my village, so I need to check the village names.
In the response above, I saw that @Dinges28 has the same question to get multipe keywords in the 'contains' field.
Is it possible to make?

**Comment by AleidusT** [comment]
I got P2000 working well, very nice.
How can I get a signal with which I can send something when a cap code is called up.

**Comment by cyberjunky** [comment]
Just use the GRIP keyword with the CAP code, its a normal search action.
