### ISSUE TITLE
Notify automation fails:

### ISSUE THREAD

**Issue by meden199** [cyberjunky/home-assistant-p2000#25]
I have a problem with the automation.

When i test the automation, no notify is send.
The log has a error:
`P2000 Bericht: Error executing script. Unexpected error for call_service at pos 1: Error rendering data template: UndefinedError: 'None' has no attribute 'attributes'
While executing automation automation.p2000_bericht
`
My automation:

`- alias: 'P2000 Bericht'
    trigger:
     platform: state
     entity_id: sensor.p2000
    action:
     - service_template: notify.pushover
       data_template:
         title: "P2000 Bericht"
         message: >
           {{ states.sensor.p2000.state + states.sensor.p2000.attributes.capcodes }}
         data:
           url: "https://www.google.com/maps/search/?api=1&query={{ states.sensor.p2000.attributes.latitude }},{{ states.sensor.p2000.attributes.longitude }}"`

Any idea what is wrong?

**Comment by cyberjunky** [comment]
Do you still have this issue?
I would first leave out the data part to see if that is the source of the problem.
