### ISSUE TITLE
No notifications with use of capcode

### ISSUE THREAD

**Issue by BebeMischa** [cyberjunky/home-assistant-p2000#26]
Firts of all, thank you very much for this nice and usefull integration. For your time spend building it.

I'm trying to get it to work, but struggle with filtering on capcodes. As long, as i don't use capcodes, everything works perfectly.
But where i do filter on capcode, no alerts are present.

Maybe i do something wrong, but i don't see it?

This is my code:

# P2000
sensor:
  - platform: p2000
    name: AMS
    regios: 13
    disciplines: 1,2,3,4
    scan_interval: 20
    icon: mdi:fire-truck
    nolocation: True

  - platform: p2000
    name: ZAAN
    regios: 11
    disciplines: 1,2,3,4
    scan_interval: 20
    icon: mdi:fire-truck
    nolocation: False

  - platform: p2000
    name: GOOI
    regios: 14
    disciplines: 1,2,3,4
    scan_interval: 20
    icon: mdi:fire-truck
    nolocation: False

  - platform: p2000
    name: KNMR
    regios: 12
    disciplines: 1,2,3,4
    scan_interval: 20
    icon: mdi:fire-truck
    nolocation: False

  - platform: p2000
    regios: 13
    name: LIFE1
    capcodes: 120901
    scan_interval: 20
    icon: mdi:helicopter
    
  - platform: p2000
    regios: 17
    name: LIFE2
    capcodes: 1420059
    scan_interval: 20
    icon: mdi:helicopter
    
  - platform: p2000
    regios: 8
    name: LIFE3
    capcodes: 923993
    scan_interval: 20
    icon: mdi:helicopter
    
  - platform: p2000
    regios: 8
    name: LIFE5
    capcodes: 923995
    scan_interval: 20
    icon: mdi:helicopter

# TOON

All the lifeliner related entry's do not show results for me...

![afbeelding](https://user-images.githubusercontent.com/73079275/98441426-76180600-20fe-11eb-97dc-40e54601deba.png)

So, can you please help me out? Thanks in advance.

**Comment by AleidusT** [comment]
Hallo BebeMischaJe kunt voor het testen ook meerdere capcodes achter elkaar zetten, komma gescheiden zonder spaties.Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: BebeMischa <notifications@github.com> Datum: 07-11-20  12:26  (GMT+01:00) Aan: cyberjunky/home-assistant-p2000 <home-assistant-p2000@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Onderwerp: [cyberjunky/home-assistant-p2000] No notifications with use of capcode (#26) 
Firts of all, thank you very much for this nice and usefull integration. For your time spend building it.
I'm trying to get in to work, but struggle with filtering on capcodes. As long, as i don't use capcodes, everything works perfectly.
But where i do filter on capcode, no alerts are present.
Maybe i do something wrongm, but i don't see it?
This is my code:
`# P2000
sensor:


platform: p2000
name: AMS
regios: 13
disciplines: 1,2,3,4
scan_interval: 20
icon: mdi:fire-truck
nolocation: True


platform: p2000
name: ZAAN
regios: 11
disciplines: 1,2,3,4
scan_interval: 20
icon: mdi:fire-truck
nolocation: False


platform: p2000
name: GOOI
regios: 14
disciplines: 1,2,3,4
scan_interval: 20
icon: mdi:fire-truck
nolocation: False


platform: p2000
name: KNMR
regios: 12
disciplines: 1,2,3,4
scan_interval: 20
icon: mdi:fire-truck
nolocation: False


platform: p2000
regios: 13
name: LIFE1
capcodes: 120901
scan_interval: 20
icon: mdi:helicopter


platform: p2000
regios: 17
name: LIFE2
capcodes: 1420059
scan_interval: 20
icon: mdi:helicopter


platform: p2000
regios: 8
name: LIFE3
capcodes: 923993
scan_interval: 20
icon: mdi:helicopter


platform: p2000
regios: 8
name: LIFE5
capcodes: 923995
scan_interval: 20
icon: mdi:helicopter


TOON `
All the lifeliner related entry's do not show results for me...

**Comment by BebeMischa** [comment]
Ja, zo had ik het eerst ook staan, alle 4 helis en alle 25 regios in een vakje. Maar ook dat gaf geen resultaat. Alles werkt prima, tot dat ik capcodes ga gebruiken.

Yes, i have started like that, all 4 choppers en all 25 regio's in one querry. But that did nod give results too. Everything works ok, until i start filtering on capcodes.

**Comment by cyberjunky** [comment]
@AleidusT thanks, I will have a look in debug mode.

**Comment by cyberjunky** [comment]
@AleidusT without looking, could it be that these messages don't contain a location? (lat/long)  In that case you need to set
nolocation: True

**Comment by AleidusT** [comment]
Heb je de juiste capcodes er wel in staan, kun je die met een vorige melding controleren.Ik heb een paar van de brandweer in één groep staan en dat werkt goed.Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: BebeMischa <notifications@github.com> Datum: 07-11-20  13:32  (GMT+01:00) Aan: cyberjunky/home-assistant-p2000 <home-assistant-p2000@noreply.github.com> Cc: AleidusT <a.r.tillema@home.nl>, Comment <comment@noreply.github.com> Onderwerp: Re: [cyberjunky/home-assistant-p2000] No notifications with use of capcode (#26) 
Ja, zo had ik het eerst ook staan, alle 4 helis en alle 25 regios in een vakje. Maar ook dat gaf geen resultaat. Alles werkt prima, tot dat ik capcodes ga gebruiken.
Yes, i have started like that, all 4 choppers en all 25 regio's in one querry. But that did nod give results too. Everything works ok, until i start filtering on capcodes.

**Comment by BebeMischa** [comment]
I will try the nolocation true option and report back, when new events happen.

Capcodes ere right, i've checked today.

**Comment by BebeMischa** [comment]
So I edited the first one like this now. To avoid some regio collission, i added all regios. And nolocation is now set to true.

  - platform: p2000
    name: LIFE1
    regios: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25
    capcodes: 120901
    scan_interval: 20
    icon: mdi:helicopter
    nolocation: True

So theoreticaly, there is no any reason for not showing a meessage for this capcode.

After a restart I wait, until there is a new even on p2000.

![afbeelding](https://user-images.githubusercontent.com/73079275/98442184-8aaacd00-2103-11eb-9a16-e9d81756b25e.png)

But still nothing here:

![afbeelding](https://user-images.githubusercontent.com/73079275/98442204-a2825100-2103-11eb-9656-f222268ef22b.png)


This is strange...

**Comment by aavosnl** [comment]
Probeer voor de lifeliners eens alleen de regio code van de standplaats.Voorbeeld amsterdam hieronder.platform: p2000
name: LIFE1
regios: 01
capcodes: 0120901
scan_interval: 20
icon: mdi:helicopter
nolocation: TrueLifeliner amsterdam wordt alleen maar gealarmeerd door hun ongeacht waar ze naar toe moeten. GroetVerzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: BebeMischa <notifications@github.com> Datum: 07-11-2020  14:15  (GMT+01:00) Aan: cyberjunky/home-assistant-p2000 <home-assistant-p2000@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Onderwerp: Re: [cyberjunky/home-assistant-p2000] No notifications with use of capcode (#26) 
So I edited the first one like this now. To avoid some regio collission, i added all regios. And nolocation is now set to true.

platform: p2000
name: LIFE1
regios: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25
capcodes: 120901
scan_interval: 20
icon: mdi:helicopter
nolocation: True

So theoreticaly, there is no any reason for not showing a meessage for this capcode.
After a restart I wait, until there is a new even on p2000.

But still nothing here:

This is strange...

**Comment by cyberjunky** [comment]
@BebeMischa the capcode in your example has a 0 in front, enter that too in P2000 config
0120901 instead of 120901

**Comment by BebeMischa** [comment]
I will try and report again. But, this has been done on your request :-)

See the Code page here in Git.
citation:
NOTE: Regarding capcodes; Make sure you specify the correct matching regio(s) in your config and remove leading 0's ie. capcode 0100001 is received as 100001

So, I've done my readings before install carefully :-P

**Comment by BebeMischa** [comment]
Stil no succes...

![afbeelding](https://user-images.githubusercontent.com/73079275/98443800-1295d480-210e-11eb-900a-c12efc27c31f.png)


![afbeelding](https://user-images.githubusercontent.com/73079275/98443808-23464a80-210e-11eb-9bc0-f91ab3331219.png)

**Comment by cyberjunky** [comment]
@BebeMischa as far as I can see is that p2000 info doesn't have any capcode info (so also not 1420059) in that message (Boshoven 8) via the feed.

**Comment by BebeMischa** [comment]
Yes, there is a capcode. The blue printed 1420059 is the correct capcode.

**Comment by cyberjunky** [comment]
@BebeMischa from which website is that capcode screenshot? I can find it in my log file, I see boshoven without it.

**Comment by BebeMischa** [comment]
https://www.p2000zhz-rr.nl/p2000-traumaheli.html

**Comment by cyberjunky** [comment]
@BebeMischa that's the issue, the component uses www.livep2000.nl, which doesn't seem to have the capcodes all events.

**Comment by BebeMischa** [comment]
oei, that's bad news... So it will not be able to do, what i intended. Maby time to change your source? :-P

**Comment by BebeMischa** [comment]
I just wanted to separate the lifeliners on my dashboard, as i'm proffessionally directly busy with them. So it had a purpose for me... I would like very much, if you could find a way to make this possible. I'm ready to assist with some testing whenever needed.

**Comment by cyberjunky** [comment]
@BebeMischa Yes maybe have the option to choose, but have to check the format, not all RSS is the same, I will have a look. 
Mabye even a seperate lifeliner component.

**Comment by BebeMischa** [comment]
I will buy you a coffee again, if you can make this work ;-)

**Comment by cyberjunky** [comment]
![p2000lifeliner](https://user-images.githubusercontent.com/5447161/98445588-b1bfc980-2118-11eb-967b-b474cad2ee2d.PNG)

;-) Give me a few minutes to get it online, for now it;s a separate component, since the URL is different and regions and disciplines are not supported with this URL.

**Comment by BebeMischa** [comment]
Oh, you are fabulous! ;-)

**Comment by BebeMischa** [comment]
Maybe i have some new interesting info.

I had a look on the website of livep2000.nl and tried to find the helis there. And i did and then i see some very rare behavior. It looks, like they give the helis a own regio, which normally not exist. Regio 28.

So i wil try that now in my config and report, if i see changes...

![afbeelding](https://user-images.githubusercontent.com/73079275/98448299-564b0700-212b-11eb-9563-356ebdb7e3f7.png)

**Comment by cyberjunky** [comment]
@BebeMischa LOL,. and I almost finished the component. ( https://github.com/cyberjunky/home-assistant-p2000lifeliners )  But I hope livep200o works and contains lat/lon for those calls, because http://feeds.feedburner.com/p2000-life-liners doesn't.

**Comment by BebeMischa** [comment]
It anyway did not work. Last enew event is not displayed. They just do not send it thru RSS. 

Their own display on the site:

![afbeelding](https://user-images.githubusercontent.com/73079275/98449029-9fea2080-2130-11eb-8293-7514308dc68b.png)

Their RSS - nothin to see between 19:22 and 19:24 hour.

![afbeelding](https://user-images.githubusercontent.com/73079275/98449011-8052f800-2130-11eb-8225-1bc5ac6acab7.png)

So with livep2000 no chance of succes :-D

**Comment by BebeMischa** [comment]
If i look thru the livep2000 RSS, they send a lot of events without capcode's. So filtering afterwards is unpossible. If we would like to do filter on capcode's, we really need to choose another source. ;-)

**Comment by BebeMischa** [comment]
When i look on p2000zhz-rr.nl, they have many different feeds. This one contains everything: http://feeds.feedburner.com/p2000-nederland. 
That feed consequently does send capcode's. So with this one as a source your original plugin will work, as intended :-)

**Comment by cyberjunky** [comment]
@BebeMischa capcodes yes, but no location data in rss feeds. I have sent them an email... Waiting for next event to test. Do you know if the lifeliners i listed here are correct?  https://github.com/cyberjunky/home-assistant-p2000lifeliners

**Comment by BebeMischa** [comment]
Yes. There also is life 4, not having own capcode, when called, mostly together with this capcode, but not everytime :-(

![afbeelding](https://user-images.githubusercontent.com/73079275/98449507-759a6200-2134-11eb-9057-c73d8ac2855e.png)

**Comment by BebeMischa** [comment]
Is your new plugin ready to test? I will give it a shot....

**Comment by BebeMischa** [comment]
Oh, and you added Medic1, i see, perfect!

**Comment by cyberjunky** [comment]
@BebeMischa it's ready to test, needed to fix some bugs, but got my first event just now.

**Comment by BebeMischa** [comment]
Ok, I've pumped it to my config now too, waiting for the party ;-)

**Comment by BebeMischa** [comment]
just for clarity, do the capcodes again start without the first zero?

**Comment by BebeMischa** [comment]
Looks promising... ;-)

![afbeelding](https://user-images.githubusercontent.com/73079275/98451853-24956880-214a-11eb-994a-c0ac5e50041c.png)

**Comment by BebeMischa** [comment]
Looks like it's not refreshing... there has been new event in Zoetermeer, but Rotterdam stays displayed. 

But anyway, you are getting closer en closer :-)

**Comment by cyberjunky** [comment]
@BebeMischa I have let it ran overnight, and have multiple event in 3 of the 5 sensors.
I see the one you mentioned too, maybe there was a delay?
I will check later what the sites says compared to my events. It seems to work, although it's a bit inefficient, all sensors grab data and update them in parallel, once fetch and update would be better.

**Comment by cyberjunky** [comment]
![CaptureLL](https://user-images.githubusercontent.com/5447161/98463428-7b875600-21bb-11eb-9608-751aad7ccad3.PNG)

**Comment by BebeMischa** [comment]
![afbeelding](https://user-images.githubusercontent.com/73079275/98463879-f30ab480-21be-11eb-9976-a2099c4c76b2.png)

**Comment by BebeMischa** [comment]
Hi, cyberjunky,

so i've tested this for a couple of days, but there still something does not work correctly. It looks, like it does not refresh properly.

Is it maybe an idea to meet each other and try to get this working flawlesly together with a cup of coffee?

**Comment by cyberjunky** [comment]
@BebeMischa sorry for the delay, a bit busy lately, I have compared the sensors and website and I indeed see sometimes delays of more than 1 hour between them, not sure what the cause is, need to look at the debug logs, and make sure the rss feed itself is not the cause. Maybe we are over stressing the feed, polling with 5 sensors every x seconds, getting blocked?

**Comment by BebeMischa** [comment]
Sorry? Never feel sorry for your volunteering ;-)

I don't know much about RSS, so i don't know, why the behaviour is not as wanted. I just do know a little about p2000 and rescue on the organisational side. So i could be helpfull by building a correctly working plugin for us all.
It only does not really flow chatting together here at Git, i think that meeting each other would be much more effective. But i also understand, if that is not wanted.

Anyway, i think, we have to look for a realy reliable source, which does provide al needed data, so the plugin would be capable to give any wanted result. as i see it now, both of the sites we use now for the two separate plugins are not good enough.

**Comment by larsoss** [comment]
can you please post you're config sesnors now you're finishd.
so i can use it ;-)

**Comment by LRvdLinden** [comment]
Hi @cyberjunky, How do I get all p2000 events from police, ambulance en fire? I only will get all the fire truck events.
<img width="262" alt="image" src="https://user-images.githubusercontent.com/77990847/107560343-8a780d00-6bdd-11eb-8c8f-020e5904830f.png">

**Comment by cyberjunky** [comment]
You can check manually if for example police data is available with your browser https://feeds.livep2000.nl?r=6&d=3
Sometime you have to add no_location: true to trigger on event without location data.
