### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Mariusthvdb** [cyberjunky/home-assistant-p2000#28]
HI,

installed this for the first time, and nothing happening so far ;-) which might be a good thing of course.

Otoh, I see this in the logs:
```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/p2000/sensor.py", line 138, in async_update
    self._event_time = self._convert_time(self._feed.entries[0]["published"])
  File "/config/custom_components/p2000/sensor.py", line 110, in _convert_time
    return datetime.datetime.strptime(time.split(",")[1][:-6], " %d %b %Y %H:%M:%S")
IndexError: list index out of range
```

which seems to indicate an issue in the CC regarding the datetime objects. I am on 118.4, and there have been more than a few issues with the datetime calculations lately.

Please check if your integration suffers that too?

thanks!

**Comment by cyberjunky** [comment]
Is this still an issue? If so please reopen.
