### ISSUE TITLE
PDW Data

### ISSUE THREAD

**Issue by denperss** [cyberjunky/home-assistant-p2000#29]
Hi Ron, 

Is it possible to add own PDW data to home assistant also ?

**Comment by cyberjunky** [comment]
@denpress, can you explain what PDW data is, and what you what to do exactly? You mean via a P2000 receiver?

**Comment by denperss** [comment]
its the same as u using in p2000 software.. 
PDW is a decoder for POCSAG messages.. 
![image](https://user-images.githubusercontent.com/59692230/107494379-ff702600-6b8e-11eb-92ae-7a7e46efba2d.png)

its using a radio that revices the POCSAG messages, decodes it and put it into a .html files. example.. 

But i see the feed u are using in your contry is a rss feed.

**Comment by cyberjunky** [comment]
Yes correct feed data only, I will close this for now.

**Comment by denperss11** [comment]
will it be possible to add own feed ?

**Comment by cyberjunky** [comment]
You mean an RSS feed? Currently not, also because the formats differ, if you have an example I can have a look.

**Comment by denperss11** [comment]
Its a html feed from pdw.. Yearh sure i can share the file with u :) 
Do u have skype where i can send u the file ?

**Comment by cyberjunky** [comment]
I think this we need a new integration/custom component. Can you tell me how you access the html file (I presume on a local server), it is one url which is constantly refreshed? If so can you post an example as zip, and the url (mask ip)

**Comment by denperss** [comment]
Okay that would be very amazing!

Yes, i have a software tool that generates a HTML, from the PDW logs filter
files. and uploads it to ftp..
i can make the html file name what i want it to be.. the file example is
here valid for 7 days [https://easyupload.io/78r3au](url)

Also im able to push out to Pushover if that can do anything better ?




Den ons. 17. feb. 2021 kl. 09.43 skrev Ron Klinkien <
notifications@github.com>:

**Comment by cyberjunky** [comment]
@denpress what is the software called which generates the html, or is it own code?

**Comment by denperss** [comment]
it was own coded, but if possible to use the flt. file from PDW software
that would be ok.

or states from Pushover would be amazing because it push it right away :)



Den tor. 18. feb. 2021 kl. 20.12 skrev Ron Klinkien <
notifications@github.com>:

**Comment by cyberjunky** [comment]
@denperss decoding the html file is easy and working, so now the question is, how to fetch it periodically?
You say it's on an ftp server right, do you need to supply user credentials, and what is the path of the file seen from your home assistant server?
What do you mean with states from pushover? I have no idea how to read messages pushed to pushover from home assistant.

**Comment by denperss** [comment]
Okay great, well the file updates automatily every time there is a new
alert it creates and upload the ftp file..
- no, the file are open and no login is requred :)

Regarding the Pushover, my on app push notification messages out to devices
trugh Pushover.
So if it was possible to intergrate like a sensor that recives it, then it
was easier and no need for fetch ftp..

Does it make sense?




Den fre. 19. feb. 2021 kl. 12.42 skrev Ron Klinkien <
notifications@github.com>:

**Comment by denperss** [comment]
Hi Ron, Any updates ?

**Comment by denperss** [comment]
Hi Ron, 
Would u be able to help me continue?

**Comment by cyberjunky** [comment]
I have to find some time... maybe this weekend.

**Comment by denperss** [comment]
Sure ofc. That would be very amazing ! Thank u :) !

**Comment by cyberjunky** [comment]
@denperss sorry I do not have enough time to code on this...

**Comment by denperss11** [comment]
Hey Ron. 

Do u think u maybe will get the time for it ?
