### ISSUE TITLE
p2000 Causes very slom start of Home assistant

### ISSUE THREAD

**Issue by maas012** [cyberjunky/home-assistant-p2000#32]
When adding the code from this p2000  in the configuration.yaml and automation.yaml,  the Home Assistant starts up very slow or even die's. When removing the p2000 code it works fine again.  HA is installed on VM VirtualBox installed on windows 10.

I have a default installation done of HA then default the automation.yaml was empty and the configuatation.yaml contains the screendump.

![defaul yaml](https://user-images.githubusercontent.com/67659312/110687899-49294c00-81e1-11eb-98e1-ec0104fa41e1.JPG)

**Comment by cyberjunky** [comment]
@maas012 Every time you restart, or just the first time? Since the first time it installs the required python components if they are not on the system.
What is the p2000 config you use?

**Comment by maas012** [comment]
Hi 
It is every time, I copied the code from your site to the conf en aut yaml also removed the automation: from your code because got a error. Even when I do not copy code in the automation.yaml so when I have a empty automation.yaml the systems start very slow.  


![configuration](https://user-images.githubusercontent.com/67659312/110825003-e2b13600-8293-11eb-933f-b0e5a896f7b3.JPG)
![automation](https://user-images.githubusercontent.com/67659312/110825033-e93fad80-8293-11eb-8ae8-9d1bca293aa0.JPG)

**Comment by cyberjunky** [comment]
@maas012 how did you install the code itself, using hacs or git clone, or copy/paste? Could be that the code has syntax errors and home assistant is starting up in rescue mode.
Also what do the logs say?

**Comment by maas012** [comment]
Installed the p2000 with hacs also did a re-installation result the same. Type a part of the code manual and file editor is green. see screen shot and did not add any code in the automation.yaml this one is empty now

Only code of p2000 is now in the configuration.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor:
  - platform: p2000
    regios: 18
    disciplines: 1,2,3,4
    scan_interval: 10
    capcodes: 1403001,1403003
    icon: mdi:fire-truck


Logfile startup ~6 minuts and see p2000 in dashboard sometime it works

[host log.txt](https://github.com/cyberjunky/home-assistant-p2000/files/6125514/host.log.txt)
[core log.txt](https://github.com/cyberjunky/home-assistant-p2000/files/6125515/core.log.txt)
[supervisor log.txt](https://github.com/cyberjunky/home-assistant-p2000/files/6125516/supervisor.log.txt)
![startup 6min](https://user-images.githubusercontent.com/67659312/110843677-db485780-82a8-11eb-8ff4-b35fe7928140.JPG)


See only 

2021-03-11 20:20:13 WARNING (MainThread) [homeassistant.loader] You are using a custom integration p2000 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

Supervisor log

21-03-11 19:20:00 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
21-03-11 19:20:00 ERROR (SyncWorker_2) [supervisor.resolution.evaluations.container] Corrupt docker overlayfs detect: 500 Server Error for http+docker://localhost/v1.40/images/sha256:345767b9a9ceb01e9eedca17ac095b6eb4862a45813feb2be81d04b3c52c8e3c/json: Internal Server Error ("readlink /mnt/data/docker/overlay2: invalid argument")
21-03-11 19:20:00 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete


But that error is there also without p2000 installed so think that not related

**Comment by maas012** [comment]
Still have the issue

**Comment by cyberjunky** [comment]
@maas012 The docker and sqlite database errors don't look good, you need to fix that.
Can you enable p2000 debug and see what comes up in the log?
https://github.com/cyberjunky/home-assistant-p2000#debugging

If you have automation announcing the p200o events, disable those for now.
Problem is that nobody reported this, and I can't reproduce it either.

**Comment by maas012** [comment]
Don't know why but everything is working fine now so very strange what causes this... But I'am happy now
