### ISSUE TITLE
Cap code question

### ISSUE THREAD

**Issue by maas012** [cyberjunky/home-assistant-p2000#33]
HI

I only want to see the certain capcodes. So how can I make only those visible, I can add some cap codes bt I need to specify also one regio so I see that regio and the cap codes

So is it possible to see only the alarms from certain cap codes ?

**Comment by cyberjunky** [comment]
@maas012 yes, just specify them in your config, it searches for anything specified under 'capcodes' parameters seperate them with comma's.

**Comment by maas012** [comment]
Is this then independed of the regios because I need to fill in at least one regio number as this could not be empty. And put now all regios and added heli cap capcodes: 120901,1420059,923993,923995  but nothing is seeing when I look to my p2000 alarm sites I see several calls for the heli but HA stay empty... Other items with only regios works fine, so whay am I doning wrong here

**Comment by cyberjunky** [comment]
@maas012 it could be that the messages don't contain location (lat/long) you need to set nolocation to True iff so.
Simply enable debug and see whats going on.

**Comment by maas012** [comment]
I found the issue the feed of feeds.livep2000.nl does not contain both cap code below only the monitorcode 120999 so that reason I had the 120901 code in it. Test it with another cap code and it works. So I can't make a special part for Trauma heli's now... So it's not a HA p2000 issue...

Thanks for the tips 


20:40:51 18-03-21 | GROUP-2 | A1 (DIA) 13991 Rit 24419 Strandweg 1976BS IJmuiden
-- | -- | --
  | 0120901 | Ambulance Amsterdam (Traumaheli Lifeliner 1 - Amsterdam)
  | 0120999 | Ambulance Amsterdam (Monitorcode)

**Comment by cyberjunky** [comment]
@maas012 some time ago I wrote a quick and dirty lifeliner integration
https://github.com/cyberjunky/home-assistant-p2000lifeliners

**Comment by maas012** [comment]
But if the lifeliner caps are not in the feed it does not work but thanks

**Comment by cyberjunky** [comment]
@maas012 did you try it? It's a different integration and uses another feed url:
BASE_URL = "http://feeds.feedburner.com/p2000-life-liners"

**Comment by maas012** [comment]
I have every thing working now fast installed HA on a raspberry and now the startup is working fine. So on a VM and Windows it does not work fine. Also the lifeliners are working also so thanks
