### ISSUE TITLE
Proefalarm

### ISSUE THREAD

**Issue by SteGe88** [cyberjunky/home-assistant-p2000#34]
In my region we sent a p2000 message when my piket will be turned over to check if the pager is set correctly, and to administer the right person on piket.

But this messages are not comming through to this component. Is that because the messages are not in the RSS feed? Or do you filter them out?

**Comment by maas012** [comment]
The script uses the https://feeds.livep2000.nl/ if the turnover should be in the feeds otherwise it will not show up in HA. So check the feeds if it is in there

**Comment by SteGe88** [comment]
Will check when there is another turnover.

**Comment by SteGe88** [comment]
I've checked the raw RSS feed, and indeed the proefalarm (turnover) isn't in the file. So I will close this issue. Thanks for your help!
