### ISSUE TITLE
Offline: https://feeds.livep2000.nl/

### ISSUE THREAD

**Issue by dutch-erik** [cyberjunky/home-assistant-p2000#36]
> RSS server offline
Wegens overmatig misbruik heeft livep2000.nl de rss server offline gehaald.
Het gevolg was dat er overbelasting ontstond.
We denken na over een oplossing, maar kunnen (helaas) geen beloften doen.
Onze oprechte excusses. 

Hopefully there is another feed we can use?

**Comment by ernieek** [comment]
Fyi we working now on a solution

**Comment by cyberjunky** [comment]
I have released version 1.0.19 just now, a bit beta maybe, basics works.
