### ISSUE TITLE
alternative?

### ISSUE THREAD

**Issue by canedje** [cyberjunky/home-assistant-p2000#37]
Will this be an alternative?

[Deze link](https://www.alarmeringdroid.nl/rssbuilder)

**Comment by ualex73** [comment]
it is an interesting one, but the location coordinates are missing - which makes it less useable.

**Comment by canedje** [comment]
a pitty

**Comment by dennisvdheuvel** [comment]
I use the link below for a while now, and not all the messages have coordinates, but a lot of them has. So, something is better than nothing? The id is the id of the last message received, based on the id you could filter out already processed messages and reduce message size.

[Link](https://www.alarmeringdroid.nl/api/livemon?regio=27&politieregio=0&id=0&prio1=false&lline=false&class=0&grip=0&dienst=&plaats=)

**Comment by cyberjunky** [comment]
I have released version 1.0.19 just now, a bit beta maybe, basics works.
