### ISSUE TITLE
Is it possible to use an own p2000 receiver and local webserver?

### ISSUE THREAD

**Issue by Dinges28** [cyberjunky/home-assistant-p2000#38]
After following the installation manual on this git: https://github.com/dmitryelj/RPi-P2000Receiver
I can now receive p2000 messages myself.

Can I use this to home-assistant p2000 messages?
And do I need to do something to get the gps positions fixed to the messages?

It feeds to an API, output:
```[{
    "body": "A1 Maerlantstraat 6531AT Nijmegen 69972",
    "capcodes": [
        "002029568",
        "000923129",
        "000923100"
    ],
    "groupid": "09.106",
    "is_posted": true,
    "message_raw": "FLEX|2021-05-27 20:39:01|1600/2/K/A|09.106|002029568 000923129 000923100|ALN|A1 Maerlantstraat 6531AT Nijmegen 69972",
    "priority": 1,
    "receivers": "002029568, 000923129, 000923100",
    "sender": 3,
    "timereceived": 1896.61824937,
    "timestamp": "2021-05-27 20:39:01"
}, {
    "body": "A2 Veldhoven Rit: 55645",
    "capcodes": [
        "001123111"
    ],
    "groupid": "09.091",
    "is_posted": true,
    "message_raw": "FLEX|2021-05-27 20:38:33|1600/2/K/A|09.091|001123111|ALN|A2 Veldhoven Rit: 55645",
    "priority": 2,
    "receivers": "001123111",
    "sender": 0,
    "timereceived": 1868.447019222,
    "timestamp": "2021-05-27 20:38:33"
}, ```

**Comment by cyberjunky** [comment]
Nice project! I will have a look, it supports websockets which is fast.
Need to write new code though,

**Comment by Dinges28** [comment]
And low investment! and not dependable (overlast) to other servers

**Comment by cyberjunky** [comment]
@Dinges28 I have it running, how do you get all capcodes to see if it's working?
Is this by default or do you have to fill capcodes.txt ??

**Comment by Dinges28** [comment]
I get all messages without naming (yet). 

I'm busy to fill (from an excel file) the capcodes.txt to get a description per capcode. 

And following the cc_police.txt, cc_fire.txt, cc_ambulance.txt. To categorize the capcodes

**Comment by Dinges28** [comment]
![image](https://user-images.githubusercontent.com/39988228/120074810-e8eacd80-c09e-11eb-810d-60afffbe1cba.jpeg)

First try with capcodes.txt filled

**Comment by cyberjunky** [comment]
Do you use an outside antenna?
I have a realtek  RTL2838UHIDIR and use the included antenna, device gets warm, so is active.
But need to check if it receives anything.

**Comment by Dinges28** [comment]
Check if it has chipset R820T, from others I've heard that it is crucial...

**Comment by cyberjunky** [comment]
Yes it has, I did some testing from command line and found out I needed to delete 'the devices, gain and correction parameters from the rtl_fm command.
I first thought I removed to much from the p2000.py code, since I run it on a beagle bone instead of a RPi I needed to change some code.
So it works now! Trying to connect to websockets...

**Comment by Dinges28** [comment]
@cyberjunky Nice!!! 
I've found a very good resource of the known capcodes, https://www.tomzulu10capcodes.nl/

Myself I still have an issue.. My time on the ubuntu vm is UTC, so... all the p2000 messages are also in UTC... now 2 hours behind.. cannot figure out where to change that in the p2000.py.. any tips?

**Comment by cyberjunky** [comment]
A quick fix:

in utils.py add this below import tzlocal

`import calendar`

in p2000.py around line 664
change this line:
`msg.timestamp = timestamp`

to:
`msg.timestamp = utils.to_local_datetime(timestamp)`

**Comment by Dinges28** [comment]
It works... In the message_raw still the UTC time, but the webview and timestamp shows now the correct time, thanx!

**Comment by esvane** [comment]
> A quick fix:
> 
> in utils.py add this below import tzlocal
> 
> `import calendar`
> 
> in p2000.py around line 664
> change this line:
> `msg.timestamp = timestamp`
> 
> to:
> `msg.timestamp = utils.to_local_datetime(timestamp)`
> 
> Add this at end of utils.py:
> 
> ```
> def to_local_datetime(utc_dt):
> 
>   time_tuple = time.strptime(utc_dt, "%Y-%m-%d %H:%M:%S")
>   t = calendar.timegm(time_tuple)
>   return time.ctime(t)
> ```

you can also remove line 664. Then it will use the time of your raspberry pi

**Comment by esvane** [comment]
I'm still having an issue with filtering/ignoring. 

I can exclude messages when entering a capcode in the capcodes_ignore.txt file. But what I want is the opposite. I want the system to exclude everything unless a specific capcode is entered.  I tried entering specific capcodes in the filter.txt file, but that does not seem to work.

**Comment by Mipilo** [comment]
> I'm still having an issue with filtering/ignoring.
> 
> I can exclude messages when entering a capcode in the capcodes_ignore.txt file. But what I want is the opposite. I want the system to exclude everything unless a specific capcode is entered. I tried entering specific capcodes in the filter.txt file, but that does not seem to work.

You can use the filter.txt to mange you capcodes

**Comment by Dinges28** [comment]
@cyberjunky Did you succeed to get messages to HA with the websocket?

I'm still working with on a decent capcode filling of the capcode files... and I'm looking on how to get the gps coordinates with an adress... I do not got a real good clue yet...

**Comment by cyberjunky** [comment]
@Dinges28 not yet, a bit lack of time, will have a new go later today.
Do you receive gps coordinates from your sdr feed, I don't think I have seen them?

**Comment by Dinges28** [comment]
No, I don't receive gps codes. They have be distilled by adress and/or postal code

**Comment by Dinges28** [comment]
maybe there is a possibility to use this website to query the addresses and get gps coordinates?

https://www.gps-coordinates.net/

**Comment by Dinges28** [comment]
It makes this query:
``curl 'https://api.opencagedata.com/geocode/v1/json?q=Prunuslaan%203053ZL%20Rotterdam&key=641c51bed8ab490184632ad8526e29ad&no_annotations=1&language=en' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Origin: https://www.gps-coordinates.net' -H 'Connection: keep-alive' -H 'Referer: https://www.gps-coordinates.net/' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache'``

And replies this xml;
``
{"documentation":"https://opencagedata.com/api","licenses":[{"name":"see attribution guide","url":"https://opencagedata.com/credits"}],"results":[{"bounds":{"northeast":{"lat":51.9655491,"lng":4.4717789},"southwest":{"lat":51.9645579,"lng":4.4697941}},"components":{"ISO_3166-1_alpha-2":"NL","ISO_3166-1_alpha-3":"NLD","_category":"road","_type":"road","city":"Rotterdam","continent":"Europe","country":"Netherlands","country_code":"nl","municipality":"Rotterdam","political_union":"European Union","postcode":"3053 JH","region":"Netherlands","road":"Prunuslaan","road_type":"residential","state":"South Holland","state_code":"ZH","suburb":"Schiebroek"},"confidence":9,"formatted":"Prunuslaan, 3053 JH Rotterdam, Netherlands","geometry":{"lat":51.9645579,"lng":4.4717789}},{"bounds":{"northeast":{"lat":51.9645579,"lng":4.4721},"southwest":{"lat":51.9644,"lng":4.4717789}},"components":{"ISO_3166-1_alpha-2":"NL","ISO_3166-1_alpha-3":"NLD","_category":"road","_type":"road","city":"Rotterdam","continent":"Europe","country":"Netherlands","country_code":"nl","municipality":"Rotterdam","political_union":"European Union","postcode":"3053 ZS","region":"Netherlands","road":"Prunuslaan","road_type":"residential","state":"South Holland","state_code":"ZH","suburb":"Schiebroek"},"confidence":9,"formatted":"Prunuslaan, 3053 ZS Rotterdam, Netherlands","geometry":{"lat":51.9644,"lng":4.4721}},{"bounds":{"northeast":{"lat":51.9034855,"lng":4.2595523},"southwest":{"lat":51.9023168,"lng":4.258378}},"components":{"ISO_3166-1_alpha-2":"NL","ISO_3166-1_alpha-3":"NLD","_category":"road","_type":"road","continent":"Europe","country":"Netherlands","country_code":"nl","municipality":"Rotterdam","political_union":"European Union","postcode":"3181 BN","region":"Netherlands","road":"Prunuslaan","road_type":"residential","state":"South Holland","state_code":"ZH","village":"Rozenburg"},"confidence":9,"formatted":"Prunuslaan, 3181 BN Rozenburg, Netherlands","geometry":{"lat":51.9028361,"lng":4.2588891}},{"bounds":{"northeast":{"lat":51.9504965,"lng":4.5660319},"southwest":{"lat":51.8593865,"lng":4.39754}},"components":{"ISO_3166-1_alpha-2":"NL","ISO_3166-1_alpha-3":"NLD","_category":"place","_type":"city","continent":"Europe","country":"Netherlands","country_code":"nl","county":"Rotterdam","political_union":"European Union","state":"Zuid-Holland","state_code":"ZH","town":"Rotterdam"},"confidence":6,"formatted":"Rotterdam, Netherlands","geometry":{"lat":51.9225,"lng":4.47917}}],"status":{"code":200,"message":"OK"},"stay_informed":{"blog":"https://blog.opencagedata.com","twitter":"https://twitter.com/OpenCage"},"thanks":"For using an OpenCage API","timestamp":{"created_http":"Tue, 22 Jun 2021 08:51:59 GMT","created_unix":1624351919},"total_results":4}
``

**Comment by cyberjunky** [comment]
> 
> 
> @cyberjunky Did you succeed to get messages to HA with the websocket?
> 
> I'm still working with on a decent capcode filling of the capcode files... and I'm looking on how to get the gps coordinates with an adress... I do not got a real good clue yet...

I have it working with posting rest to HA now, much easier to setup, will try to get something out soon, even thinking about creating a HASS addon from it. So the RTLSDR stick can be put in my HA server.

Where can I get most accurate capcodes? (the numbers, names and types)

![image](https://user-images.githubusercontent.com/5447161/123508659-02b50b80-d671-11eb-9c73-24c87e5b09d7.png)

**Comment by Dinges28** [comment]
> > @cyberjunky Did you succeed to get messages to HA with the websocket?
> > I'm still working with on a decent capcode filling of the capcode files... and I'm looking on how to get the gps coordinates with an adress... I do not got a real good clue yet...
> 
> I have it working with posting rest to HA now, much easier to setup, will try to get something out soon, even thinking about creating a HASS addon from it. So the RTLSDR stick can be put in my HA server.

That would be a nice feature, but....

Does it have to be on the same server? Because my RTLSDR is not able to be on my hass server it is on a seperate one.

> 
> Where can I get most accurate capcodes? (the numbers, names and types)

Capcode site: https://www.tomzulu10capcodes.nl/ there is an excel file that is accurate maintained
> 
> ![image](https://user-images.githubusercontent.com/5447161/123508659-02b50b80-d671-11eb-9c73-24c87e5b09d7.png)


The GPS matching..
I have found the website https://opencagedata.com
You can make a free account, 2500 queries per 24hours for unlimited time; if the "test" p2000 messages are filtered out, that would do for a "normal" day.
For instance, I just want to query 2 regions for all the messages, and all the regions for GRIP messages, if GPS check after the filtering takes place, it will probably not even make 300-500 checks per day...

**Comment by cyberjunky** [comment]
@Dinges28 the python script is destilled from the RPiReceiver one, with all the extras taken out.
So it can run on a seperate server, I do that now too.

Did you manage to substract the address part to look up a gps location from the message? Have code?

**Comment by cyberjunky** [comment]
I have found this one: http://p2000.bommel.net/caplist.php?r=Zuid-Holland%20Zuid&d=Politie&sort=korps,capcode

Click on 'csv' link, it looks more complete, but not sure if amount is the same.

**Comment by Dinges28** [comment]
> @Dinges28 the python script is destilled from the RPiReceiver one, with all the extras taken out.
> So it can run on a seperate server, I do that now too.
> 
> Did you manage to substract the address part to look up a gps location from the message? Have code?

No, I didn't have made code.. I'm not into python coding.. it keeps failing (my best python is copy-paste-trial-error ;-)  But I try, but did not get any successfull thing....

But from my perspective, find and replace and regex could do the trick.
-first search in the body to a postal code 0000AB that could be done by a regex, i think?
-strip all the know full-word-p2000 code like "Rit ???" "Prio" "A1"  any of that kind of stuff... and you probably will end up with a address
-citynames (KATWZH) like in your example convert to real city names, there is in the zulu excel sheet a tab with city names... 

Is that an option?

**Comment by Dinges28** [comment]
> I have found this one: http://p2000.bommel.net/caplist.php?r=Zuid-Holland%20Zuid&d=Politie&sort=korps,capcode
> 
> Click on 'csv' link, it looks more complete, but not sure if amount is the same.

The zulu1 has also all the not yet actively used numbers indexed like fire/ambu/pol/red category... Will have to check the filled fields and count how much it is.. will do that tomorrow

**Comment by cyberjunky** [comment]
I managed to extract the postcodes, but I guess that 75% of the message don't contain one, for City or streetname maybe 50%.
Added some other details as well...
Will have a look at the zulu city names.

![Screenshot from 2021-06-27 11-34-10](https://user-images.githubusercontent.com/5447161/123539834-ee8a1080-d73b-11eb-8d2c-c39a336f5752.png)

**Comment by Mipilo** [comment]
> > I have found this one: http://p2000.bommel.net/caplist.php?r=Zuid-Holland%20Zuid&d=Politie&sort=korps,capcode
> > Click on 'csv' link, it looks more complete, but not sure if amount is the same.
> 
> The zulu1 has also all the not yet actively used numbers indexed like fire/ambu/pol/red category... Will have to check the filled fields and count how much it is.. will do that tomorrow

I've found out that there isn't a full list of all capcodes. Most sites show the capcodes that are used in the last month. Maybe because capcodes change every now and then?
It is a pity because some emergency services (such as the fire department ) are not deployed monthly for a calamity.

So I think you will have to update the list every month...

**Comment by Mipilo** [comment]
@cyberjunky, If you're looking for testers, I'd be happy to help out!!

**Comment by Dinges28** [comment]
> I managed to extract the postcodes, but I guess that 75% of the message don't contain one, for City or streetname maybe 50%.
> Added some other details as well...
> Will have a look at the zulu city names.
> 


@cyberjunky If I check with the original feed's his discription, livep2000 -> techniek 
They also have this problem. 
Distilling gps from the massages will never be 100% complete. 
I see in region flevoland and amsterdam-amstelland really a lot messages with some kind of adress (postal code and/or streetname)
(maybe also a check, if the p2000 message is already having the gps coordinates?)



> ![Screenshot from 2021-06-27 11-34-10](https://user-images.githubusercontent.com/5447161/123539834-ee8a1080-d73b-11eb-8d2c-c39a336f5752.png)

This looks already really promising!!!

**Comment by cyberjunky** [comment]
@Mipilo @Dinges28 
First release (beta)
https://github.com/cyberjunky/RTL-SDR-P2000Receiver-HA

**Comment by Dinges28** [comment]
@cyberjunky  Nice First Release Rob! 

Works like a charm!
Yes, all the messages come to HA now, but that is as designed/described in the release.

Do you want to shoot issues/results/suggestions here or in the issuelist on the repo itself?

**Comment by cyberjunky** [comment]
I guess opening an issue in that repo is better.

**Comment by Mipilo** [comment]
Thanks @cyberjunky it works like a charm!
