### ISSUE TITLE
Sensor not responding

### ISSUE THREAD

**Issue by ArnoS57** [cyberjunky/home-assistant-p2000#45]
I have this P2000 sensor in my configuration.yaml 
I tried to have more “contains” words but no call could be seen
I separated it with comma’s
What am I doing wrong?

  - platform: p2000
    scan_interval: 10
    name: BRW-NL
    contains: GRIP,(Middel BR),(Grote BR), (Zeer gr. BR)
    icon: mdi:alarm-light
    nolocation: true

**Comment by cyberjunky** [comment]
Only support one entry
