### ISSUE TITLE
State of intergration.

### ISSUE THREAD

**Issue by Danielson187** [cyberjunky/home-assistant-p2000#46]
Hi Guys,

I've used this intergration since a long time and it's great! But i'm a bit lost on the current state? 

I can't get it to work anymore, can we still use the radius with latitude and longitude?

I'm in region 5, how can i get this great intergration back online again?

**Comment by ictfreak** [comment]
- platform: p2000
    name: P2000 Regio Twente
    regios: 5
    nolocation: true

**Comment by cyberjunky** [comment]
Do you still have this issue?
