### ISSUE TITLE
Since a couple off days or so no new messages

### ISSUE THREAD

**Issue by canedje** [cyberjunky/home-assistant-p2000#47]
Is there something changed?
I do not receive messages anymore for a day or 2 or so?

EDIT:
If I do activate "nolocation" I do receive push notifications again, but without location.
None off the notifications do have location info.
This is producing to much notifications for me
My configuration. Yaml:

```
#----------------------------------------------------------------      
# Sensoren voor p2000
# Regio 10 = Noord Holland Noord
#----------------------------------------------------------------
    
- platform: p2000
  name: P2000
  regios: 10
#  disciplines: 1,2,3,4
  radius: 5000
  scan_interval: 20
#  capcodes: 1403001,1403003
  icon: mdi:alarm-light
  nolocation: true
```

**Comment by roosenbrug** [comment]
Same problem here. Since 18-8-2021 no updates anymore.

**Comment by MagieMalone** [comment]
yep, same issue, my last message is from  August 18, 2021, 19:55:39, also regios: 10

**Comment by mobiledude** [comment]
same here. did development stop?

**Comment by scns** [comment]
same issue here. no data. @cyberjunky, can you please check? 

I used the YAML below"

`- platform: p2000
  name: LN
  regios: 23
  radius: 15000
  scan_interval: 10

- platform: p2000
  name: Amsterdam
  regios: 13
  disciplines: 1,2,3,4
  radius: 10000
  scan_interval: 10
  latitude: 52.3680
  longitude: 4.9036`

The RSS feed in te code is still responding.

**Comment by scns** [comment]
I see when I take a look to the RSS feed that the Lat en Long are empty for al items.

```
<item>
<title>1403319 - P 2 BRT-01 OMS brandmelding Zorgwaard, Korenschoof Wouter van den Walestr Heinenoord 185731</title>
<code>1403319</code>
<message>P 2 BRT-01 OMS brandmelding Zorgwaard, Korenschoof Wouter van den Walestr Heinenoord 185731</message>
<lon/>
<lat/>
<RegCode>18</RegCode>
<RegName>Zuid-Holland Zuid</RegName>
<Dienst>Brandweerdiensten</Dienst>
<author>P2000 Livemonitor 2021 HomeAssistant</author>
<link>http://p2000.brandweer-berkel-enschot.nl/LiveMonitor.aspx</link>
<category>P2000</category>
<pubDate>Thu, 9 Sep 2021 14:43:31 +0100</pubDate>
<guid/>
</item>
```

Look's like that is the problem?

**Comment by canedje** [comment]
> I see when I take a look to the RSS feed that the Lat en Long are empty for al items.
> 
> ```
> <item>
> <title>1403319 - P 2 BRT-01 OMS brandmelding Zorgwaard, Korenschoof Wouter van den Walestr Heinenoord 185731</title>
> <code>1403319</code>
> <message>P 2 BRT-01 OMS brandmelding Zorgwaard, Korenschoof Wouter van den Walestr Heinenoord 185731</message>
> <lon/>
> <lat/>
> <RegCode>18</RegCode>
> <RegName>Zuid-Holland Zuid</RegName>
> <Dienst>Brandweerdiensten</Dienst>
> <author>P2000 Livemonitor 2021 HomeAssistant</author>
> <link>http://p2000.brandweer-berkel-enschot.nl/LiveMonitor.aspx</link>
> <category>P2000</category>
> <pubDate>Thu, 9 Sep 2021 14:43:31 +0100</pubDate>
> <guid/>
> </item>
> ```
> 
> Look's like that is the problem?

So we need to find a new RSS feed?

**Comment by scns** [comment]
Looks like this RSS feed is special made for this app. So finding another is not so easy I thing.

Or we need to find a source what has all the data this app needs.

When there is a valid source i have the possibility to create a RSS feed. 

But the easiest way is of course that he original RSS feed is fixed

**Comment by mobiledude** [comment]
@cyberjunky do you still get data from ernieek? Is he still around to help out to fix this if possible?

**Comment by cyberjunky** [comment]
@mobiledude no contact, i guess the GPS service is down?

You can also buy a raspberry Pi and RTL-SDR dongle and receive it yourself, we have GPS service Opencage included which is free for limited # of lookup. See here.
https://github.com/cyberjunky/RTL-SDR-P2000Receiver-HA
But you can currently only configure 1 sensor.

**Comment by Maximus48p** [comment]
lees hier:
[https://www.livep2000.nl/index.php?p=rssfeedsInfo]

**Comment by cyberjunky** [comment]
> lees hier:
> https://www.livep2000.nl/index.php?p=rssfeedsInfo

We don't use that one for a long time, we use this one:
http://p2000.brandweer-berkel-enschot.nl/homeassistant/rss.asp

But maybe the same issue/challenge.

**Comment by cyberjunky** [comment]
Working again it seems.

**Comment by MagieMalone** [comment]
maybe the site is working again, but the integration doesn't produce anything. I have all messages in region 10 as a sensor, and no message has been selected since 18/8/2021 while on livep2000.nl I see several messages for the last hour alone.
```
sensor:
  - platform: p2000
    name: p2000_latest
    regios: 10
```

**Comment by cyberjunky** [comment]
Add nolocation = True, or update to latest version 1.0.21

**Comment by canedje** [comment]
It is working again. Nice.
Is it possible to check on different contains, seperated bij a , ?
Like:
  contains: Heerhugowaard, Heiloo

?

**Comment by MagieMalone** [comment]
you can do that in homeassistant for instance with a template sensor or on any automation that you trigger by:
```
- "{{trigger.to_state is  search('Lutjebroek|Grootebroek|Hoogkarspel', ignorecase=true)}}"
```
in a template you would lookup the original sensor and of course not the trigger.

**Comment by canedje** [comment]
Thanks for the answer.
I like to make an template.
I'm a noob in making templates.
Will this work?
    p2000_trigger:
      friendly_name: "P2000 Trigger"
      value_template: "{{ (states('sensor.p2000') | search('Lutjebroek|Grootebroek|Hoogkarspel', ignorecase=true))}}"

**Comment by MagieMalone** [comment]
probably this:
```
sensor:
  - platform: template
    sensors:
      p2000_trigger:
        value_template: >
          {% if states('sensor.p2000') is search('Lutjebroek|Grootebroek|Hoogkarspel', ignorecase=true) %}
            {{states('sensor.p2000')}}
          {% else %}
            {{states('sensor.p2000_trigger')}}
          {% endif %}
        attribute_templates:
          discipline: >
            {% if states('sensor.p2000') is search('Lutjebroek|Grootebroek|Hoogkarspel', ignorecase=true) %}
              {{state_attr('sensor.p2000', 'discipline')}}
            {% else %}
              {{state_attr('sensor.p2000_trigger', 'discipline')}}
            {% endif %}
```
and repeat the last bit for every attribute you wan to copy from the original sensor. I haven't tested it, but syntax  passes visual studio code problem inspection

**Comment by canedje** [comment]
Thanks for the help!
