### ISSUE TITLE
Radius not working

### ISSUE THREAD

**Issue by berg78** [cyberjunky/home-assistant-p2000#49]
Hello,

I am still a beginner with HA, i have added the integration, but my radius is not working, i recieve all alarms from Limburg Zuid.
Can someone tell me what i am doing wrong? 

Here is my config:

# P2000
  - platform: p2000
    name: LimburgZuid
    scan_interval: 20
    icon: mdi:fire-truck
    nolocation: true
    regios: 24
    radius: 5000
    scan_interval: 20
    latitude: 50.942440
    longitude: 5.886460

**Comment by cyberjunky** [comment]
Because of missing location data I guess
