### ISSUE TITLE
No any new info since two days

### ISSUE THREAD

**Issue by BebeMischa** [cyberjunky/home-assistant-p2000#53]
Hello guys,

last two days I get no more info on any sensor.

Last recorded message is from 27.11 07:16:32

the RSS server http://p2000.brandweer-berkel-enschot.nl/homeassistant/rss.asp looks down, errorcode 500.

Please, have a look at it ;-)

**Comment by lowieh** [comment]
the same issue here

**Comment by lowieh** [comment]
hij is weer in de lucht!!

**Comment by BebeMischa** [comment]
werkt weer.
