### ISSUE TITLE
geolocation not working

### ISSUE THREAD

**Issue by bsmeding** [cyberjunky/home-assistant-p2000#57]
I have a small radius from my house, but receive all messages from this regio.

```
  - platform: p2000
    name: p2000 thuis
    regios: 12
    radius: 2000
    scan_interval: 10
```

It looks like the problem is the lat/long always 0 / 0 (from last 2000 messages all where 0/0)

Example:
`A2 10104 Rit 160113 VWS Wognum`. (more than 50 km from home)
```
longitude: 0
latitude: 0
distance: 0
capcode: '0126999'
regio: '12'
regio name: Kennemerland
discipline: Ambulancediensten
time: '2021-12-16T13:53:55'
attribution: P2000 Livemonitor 2021 HomeAssistant
friendly_name: p2000 thuis
icon: mdi:ambulance
```

Is there something to fix the geolocation?

**Comment by bsmeding** [comment]
I now read about new P2000 source (feed), didn't used the P2000 for couple of weeks and was working well before. I guess the problem is the new source.

**Comment by six-shooter** [comment]
I am having the same problem, is there any way to solve this?

**Comment by bsmeding** [comment]
Not found yet, there is no feed I found so far that delivers geo ip information. 

Think this must be created in the module to do lookup based on information. Only the P2000 messages are not consistent in sending the address information

**Comment by bsmeding** [comment]
In meanwhile is is working for most of the messages for a couple of weeks now. Think this can be closed now

**Comment by cyberjunky** [comment]
Look at my other project where we try to get as much address information as possible from each message, get street, city and even geo-location data using a free third party service. https://github.com/cyberjunky/RTL-SDR-P2000Receiver-HA it works pretty solid, you have to have a RTLSDR dongle and a Raspberry Pi though.

**Comment by ArnolddeBolster** [comment]
posted in new issue: the old feed still contains lon/lat

**Comment by ArnolddeBolster** [comment]
and another one with lon/lat https://melding.p2000alarm.nl/

**Comment by ArnolddeBolster** [comment]
I now use an extra p2000 integration only just for plotting on map because it contains lon\lat.
Maybe you can add it or use it in this integration ?
https://alarmeringdroid.nl/api2/find/

**Comment by ArnolddeBolster** [comment]
problem solved, feed is working again
