### ISSUE TITLE
P2000 Source offline - slow Home Assistant

### ISSUE THREAD

**Issue by martijntenpas** [cyberjunky/home-assistant-p2000#60]
Last weekend the source http://p2000.brandweer-berkel-enschot.nl/ was offline. I'm running with a interval of 1 second (i'm firefighter and using it to put on the lights at night). It triggers a lot of exeptions (TimeoutError: [Errno 110] Operation timed out) in the log, and after serval minutes HA starts to responding very slow. After disabling the P2000 integration everything is working fine again.

**Comment by beffin** [comment]
Same problem here. I reload it every 2 seconds because I am also a firefighter. It slows down my Home Assistant so much that it runs unstable.

Hopefully a solution can be found for this, because I really appreciate the integration!

**Comment by HenkSnavel** [comment]
@cyberjunky i found another p2000 component which uses https://beta.alarmeringdroid.nl/api2/find/ maybe a option te replace http://p2000.brandweer-berkel-enschot.nl/

**Comment by dutch-erik** [comment]
I see you found it: https://github.com/leeuwte/home-assistant-p2000 🙂

**Comment by ArnolddeBolster** [comment]
problem solved, feed is working again
