### ISSUE TITLE
P2000 berkel enschot down?

### ISSUE THREAD

**Issue by aavosnl** [cyberjunky/home-assistant-p2000#62]
Good evening,

I haven't been getting any new alerts since about 7:30 PM.

Is there anything known about a malfunction in the feed from p2000 Berkel Enschot?

**Comment by aavosnl** [comment]
And again, the feed is down.... 

Is there any backup or an other feed?

**Comment by Wally112** [comment]
Would like to see a backup as well!

**Comment by cyberjunky** [comment]
I'm not providing the feed myself, so cannot help unfortunatly. Closing for now.
