### ISSUE TITLE
Feedwebsite down, no data available.

### ISSUE THREAD

**Issue by BebeMischa** [cyberjunky/home-assistant-p2000#68]
Hello guys,

since this morning it look, that http://p2000.brandweer-berkel-enschot.nl/LiveMonitor.aspx does not generate any live data.

So our sensors follow the silence ;-)

Thank you for looking in to it

**Comment by BebeMischa** [comment]
Never mind, it started working again.

**Comment by svptje** [comment]
Feed does work, unfortunately the lon and lat information is currently missing

**Comment by BebeMischa** [comment]
Since yesterday the feeding site is again not generating any data :-(

**Comment by cyberjunky** [comment]
The feed is not mine, so sorry cannot fix it. I suggest to look at the new integration with where you can receiver your own signals from the air using a cheap RTL-SDR receiver.
https://github.com/cyberjunky/addon-p2000_rtlsdr
