### ISSUE TITLE
No more geolocation

### ISSUE THREAD

**Issue by HA-Peet** [cyberjunky/home-assistant-p2000#69]
Since RSS was restarted several days ago, no more geolocation on P2000 alarms.

**Comment by svptje** [comment]
Geolocation is werking again! Thanks!

**Comment by svptje** [comment]
RSS feed is down. Is it possible to share the code, as I might be able to setup a backup feed? But currently I do not have the knowledge to create it on my own. I already have the [RTL-SDR-P2000Receiver-HA](https://github.com/cyberjunky/RTL-SDR-P2000Receiver-HA) running on a pi. But it does not have the ability to write to a DB and I have absolutely no knowledge on how to do that.
