### ISSUE TITLE
Rlast item SS down

### ISSUE THREAD

**Issue by HA-Peet** [cyberjunky/home-assistant-p2000#73]
last: <pubDate>Tue, 13 Dec 2022 10:20:19 +0100</pubDate>

**Comment by BebeMischa** [comment]
I also don't receive any data on two HA systems since yesterday...

**Comment by Mbruins** [comment]
http://p2000.brandweer-berkel-enschot.nl/homeassistant/rss.asp Feed is down.

**Comment by BebeMischa** [comment]
works again here ;-)
