### ISSUE TITLE
Unique ID

### ISSUE THREAD

**Issue by ArthurvdMolen** [cyberjunky/home-assistant-p2000#74]
In HA i get this error: This entity does not have a unique ID? Is it possible to generate them for this add-on?

Deze entiteit ("sensor.p2000") heeft geen unieke ID, daarom kunnen de instellingen ervan niet worden beheerd vanuit de gebruikersinterface. Zie [documentatie](https://www.home-assistant.io/faq/unique_id) voor meer details.

This entity ("sensor.p2000") does not have a unique ID, therefore its settings cannot be managed from the user interface. See documentation for more details.

**Comment by matthiasdebaat** [comment]
Would love this too, to hide the sensor on my default dashboard. Thanks for this nice integration!

**Comment by cyberjunky** [comment]
I added it to version 1.0.23, which should appear in your HA any minute!

**Comment by matthiasdebaat** [comment]
That was quick! 🥳 Thanks and a Happy New Year!
