### ISSUE TITLE
Live feed stopped @ 3 Jan 2023 - http://p2000.brandweer-berkel-enschot.nl/LiveMonitor.aspx

### ISSUE THREAD

**Issue by adekloet** [cyberjunky/home-assistant-p2000#75]
No P2000 updates on the feed URL: http://p2000.brandweer-berkel-enschot.nl/LiveMonitor.aspx
Last update 3 Jan 2023 14:18

**Comment by aavosnl** [comment]
Die feed stopt  er heel vaak mee. Denk dat zijn buffer dan vol loopt of iets.Na een handmatige herstart door die site beheerder gaat het weer even goed. Niets ten nadele van het goede werk door deze mensen het is namelijk een welkome toevoeving in home assistant. Alleen het vol of vastlopen van de feed  dmv een automatische herstart vam de feed zou mooi zijn Groet
-------- Oorspronkelijk bericht --------Van: Alex de Kloet ***@***.***> Datum: 04-01-2023  13:11  (GMT+01:00) Aan: cyberjunky/home-assistant-p2000 ***@***.***> Cc: Subscribed ***@***.***> Onderwerp: [cyberjunky/home-assistant-p2000] Live feed stopped @ 3 Jan 2023 - http://p2000.brandweer-berkel-enschot.nl/LiveMonitor.aspx (Issue #75) 
No P2000 updates on the feed URL: http://p2000.brandweer-berkel-enschot.nl/LiveMonitor.aspx
Last update 3 Jan 2023 14:18
