### ISSUE TITLE
Live feed

### ISSUE THREAD

**Issue by joelnoorland** [cyberjunky/home-assistant-p2000#77]
Live feed werkt niet meer vanaf vanochtend 09:00 ongeveer waardoor ik geen meldingen meer binnen krijg in mijn HA.

**Comment by Roedie84** [comment]
Same issue here

**Comment by ariekraakjr** [comment]
Als je in custom_components/p2000/sensor.py onderstaande aanpassing doet werkt het weer.

#CONF_ATTRIBUTION = "P2000 Livemonitor 2021 HomeAssistant"
CONF_ATTRIBUTION = "2021 HomeAssistant live p2000 monitor"

**Comment by cyberjunky** [comment]
The feed is not mine, so sorry cannot fix it. I suggest to look at the new integration with where you can receiver your own signals from the air using a cheap RTL-SDR receiver.
https://github.com/cyberjunky/addon-p2000_rtlsdr
