### ISSUE TITLE
No update of sensor

### ISSUE THREAD

**Issue by aavosnl** [cyberjunky/home-assistant-p2000#8]
Just installed everything following the workaround. Looks like the app dont get an update from the feed. Selecting al regions and the app stays on unknown.

**Comment by aavosnl** [comment]
A part of mij sensors.yaml file 
sensor:
  - platform: buienradar
    monitored_conditions:
      - symbol
      - humidity
      - temperature
      - windspeed
      - pressure
sensor:
  - platform: p2000
    regios: 18
    disciplines: 1,2,3,4
    scan_interval: 20
    capcodes: 1403001,1403003
  
  - platform: p2000
    name: Amsterdam
    regios: 13
    disciplines: 1,2,3,4
    radius: 10000
    scan_interval: 10
    latitude: 52.3680
    longitude: 4.9036

the sensor p2000 and sensor amsterdam are visible in home assistant.  Looks like n data is received,

**Comment by aavosnl** [comment]
![sensor1](https://user-images.githubusercontent.com/24371158/76120676-473b1480-5ff2-11ea-93df-ff38a0999711.JPG)
![sensor2](https://user-images.githubusercontent.com/24371158/76120681-4904d800-5ff2-11ea-82d6-63b0133674e4.JPG)
![configyaml](https://user-images.githubusercontent.com/24371158/76120684-4ace9b80-5ff2-11ea-8d25-99d71b4b38c6.JPG)

**Comment by aavosnl** [comment]
![configyaml1](https://user-images.githubusercontent.com/24371158/76121052-1dceb880-5ff3-11ea-8f66-0f18ef88427b.JPG)
![sensor3](https://user-images.githubusercontent.com/24371158/76121057-1effe580-5ff3-11ea-842b-5af4d9156aab.JPG)

**Comment by ualex73** [comment]
Yups, same here - reverted back to the previous version resolved it.

**Comment by aavosnl** [comment]
Uninstalled everything, install version 1.0.4 but sensor info stays @ unknown.  Leaving for now just as it is. waiting couple of hours to see of something will happen and the sensor get some information

**Comment by harryd100** [comment]
same here, going to revert if possible

**Comment by sweetpants** [comment]
1.0.8 works when adding capcodes

- platform: p2000
  regios: 19
  disciplines: 1,2,3,4
  capcodes: 1320108,1320001,1303836,1301086,1300001,1330101
  scan_interval: 10
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 25000

**Comment by cyberjunky** [comment]
Sorry for the bugs, can you test Release 1.0.9?
Just copy the latest sensor.py file, or wait for HACS to pickup update to show up.

**Comment by ualex73** [comment]
Installed 1.0.9 and I see p2000 messages again.

**Comment by aavosnl** [comment]
Installed 1.0.9  first only the sensor based on
- platform: p2000
    name: Amsterdam
    regios: 13
    disciplines: 1,2,3,4
    radius: 10000
    scan_interval: 10
    latitude: 52.3680
    longitude: 4.9036

was working another sensor with code 
- platform: p2000
    name: ambu test
    regios: 13
    disciplines: 1,2,3,4
    scan_interval: 10
    capcodes: 0120999

stays on unknown. After a wile i'f noticed that the used feed al the capcodes starting with a 0  (012099)  in the feed where missing the first 0.  deleted that form the code and changed it to 

- platform: p2000
    name: ambu test
    regios: 13
    disciplines: 1,2,3,4
    scan_interval: 10
    capcodes: 120999

solved the problem and the sensor is getting updates

**Comment by aavosnl** [comment]
> 
> 
> Sorry for the bugs, can you test Release 1.0.9?
> Just copy the latest sensor.py file, or wait for HACS to pickup update to show up.

Why say sorry :) let al the users say thanks for your time and work on it.   Bugs happen  and thats no problem at all.

**Comment by r3mcos3** [comment]
for me still no updates with latest update.

`- platform: p2000
  name: Brabant
  regios: 20,21,22
  disciplines: 1,2,3,4
  scan_interval: 90`

i don't use capcodes.

**Comment by cyberjunky** [comment]
I though I had tested all different combinations..
It looks like there are a lot of msgs without a location, testing a fix.

**Comment by r3mcos3** [comment]
with this config it's working again.

```
---
- platform: p2000
  name: Brabant
  regios: 20,21,22
  disciplines: 1,2,3,4
  scan_interval: 90
  latitude: 55.581461
  longitude: 9.011954
  radius: 10000
```

maybe it can't fetch the location off home assistant.
because if i give it a specific location it's working.

**Comment by cyberjunky** [comment]
Try release 1.0.10 it should show up soon in HACS, or copy from github.

**Comment by morrisb74** [comment]
Still the same - Says unknown and doesn't update

**Comment by r3mcos3** [comment]
updated to 1.0.10 and i removed latitude, longitude, radius. 
and for me it's working again!

**Comment by cyberjunky** [comment]
> Still the same - Says unknown and doesn't update

Are you sure?
I tested with all the configs combo's I could think of.
What does yours look like?

**Comment by r3mcos3** [comment]
now i have this 
```
- platform: p2000
  name: Brabant
  regios: 21
  disciplines: 1,2,3,4
  # scan_interval: 90
  # latitude: 51.581461
  # longitude: 5.011954
  radius: 25000
```
because off the huge notifications that's is coming in

![Screenshot_20200310_194937](https://user-images.githubusercontent.com/45529818/76348454-83c78280-6308-11ea-9d64-26683bc4ab1e.png)

**Comment by aavosnl** [comment]
After updating, dont get updates on the sensors thats using 01,02,03,04,05,06,07,08,09  capcodes al others are working. The option to leave the first 0 isn't working anymore

**Comment by cyberjunky** [comment]
Can you grab some debug logging?

**Comment by cyberjunky** [comment]
Closing, if there are still problems with latest release please open a new github issue.
