### ISSUE TITLE
Integration no longer working

### ISSUE THREAD

**Issue by jvrossum** [cyberjunky/home-assistant-p2000#80]
Homeassistant (2023.8.4) returns the following message when checking the Entity:

This entity is no longer available from the p2000 integration. When the entity is no longer in use, it can be deleted from the settings.

Config:
  - platform: p2000
    scan_interval: 20
    icon: mdi:fire-truck
    nolocation: true

and 

  - platform: p2000
    name: FlevolandGooi
    regios: 25

**Comment by ArnolddeBolster** [comment]
Please make it stable again and please with lon/lat included

the new feed is very unstable and the old one https://[feeds.livep2000.nl](https://feeds.livep2000.nl/)/ still works.
please restore the old one or another feed as mentioned in other issues.

**Comment by cyberjunky** [comment]
I do not host the feed, so cannot fix it, this integration is dead... buy a cheap RTL-SDR stick and use this add-on, so you read and calculate things yourself. https://github.com/cyberjunky/RTL-SDR-P2000Receiver-HA I use it myself 
![image](https://github.com/cyberjunky/home-assistant-p2000/assets/5447161/ed15f383-13db-486d-b86d-5634d2ece9e1)

**Comment by williamabbo** [comment]
And the RTL-stick icm with a Raspberry is working like a charm.
Running here for about 2 years without any fail.

**Comment by ArnolddeBolster** [comment]
Not everybody wants or needs extra hardware, so in my opinion continue your new p2000 integration with RTL stick and downgrade a p200 integration without RTL stick. It worked for many without the stick with the old integration. Seperate both solution so everybody can decide to use the old or more stable integration

the latest rss feed doesn't work anymore while other feeds do. If you decide to support only the RTL version then please withdraw this HACS integration

And your new RTL integration is too complex and have no room for a RTL-stick.

**Comment by ArnolddeBolster** [comment]
integration is working again
