### ISSUE TITLE
Feed site down again

### ISSUE THREAD

**Issue by BebeMischa** [cyberjunky/home-assistant-p2000#82]
http://p2000.brandweer-berkel-enschot.nl/LiveMonitor.aspx

is dead again.

;-)

**Comment by cyberjunky** [comment]
The feed is not mine, so sorry cannot fix it. I suggest to look at the new integration with where you can receiver your own signals from the air using a cheap RTL-SDR receiver.
https://github.com/cyberjunky/addon-p2000_rtlsdr
