### ISSUE TITLE
Feed werkt niet

### ISSUE THREAD

**Issue by sjefke09** [cyberjunky/home-assistant-p2000#83]
Ik krijg deze fout:
DEBUG (MainThread) [custom_components.p2000.sensor] Error parsing feed data from http://p2000.brandweer-berkel-enschot.nl/homeassistant/rss.asp

Dit is bij onderstaande config:
sensor:
  - platform: p2000
    name: P2000 Thuis
    regios: 23
    scan_interval: 10

**Comment by ArnolddeBolster** [comment]
problem solved, feed is working again
