### ISSUE TITLE
radius not working

### ISSUE THREAD

**Issue by bsmeding** [cyberjunky/home-assistant-p2000#9]
with the lasted update, the radius setting is not applied. I get all the messages from the region instead of 3000m radius

**Comment by cyberjunky** [comment]
I tested almost every possible combination successfully, also radius.

My guess is that the events reported don't have a lat/lon value, can you check this?
If they have a lat/long value, post your config and debug log info so I can look at it.

**Comment by bsmeding** [comment]
hi ciberjunky,

that is correct I think, but all events are missing the lat long. Normally I have around 20 messages a day and now above 400.

'''
sensor:      
    - platform: p2000
      name: p2000 kennemerland
      regios: 12
      disciplines: 1,2,3
      radius: 3000
      scan_interval: 30
      latitude: 52.43xxxx
      longitude: 4.66xxxx
'''

what / how do you want the debug info from?

**Comment by cyberjunky** [comment]
Most of the non lat/lon containing messages are copies of ones with lat/lon and short chat like msgs, depending on the region there can be many.

Last line added to your logger section will generate all output.
```
logger:
  default: info
  logs:
      custom_components.p2000: debug
```

**Comment by cyberjunky** [comment]
You can also install release 1.0.11 as see how that works.

**Comment by bsmeding** [comment]
Yes will do, just upgraded and rebooted HASS, waiting for an P2000 message now

**Comment by bsmeding** [comment]
It is working now! thanks for the fix and update. Messages are filtered correctly again
